name: Update file from latest release

on:
  workflow_dispatch:

permissions:               
  contents: write           
  pull-requests: write

jobs:
  update-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get latest release info
        id: get_release
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.WORKLOG_GITHUB_TOKEN }}
          script: |
            const { data: latestRelease } = await github.rest.repos.getLatestRelease({
              owner: 'evolvedlight',
              repo: 'WorklogAssistant',
            });
            core.setOutput('tag_name', latestRelease.tag_name);
            core.setOutput('tarball_url', latestRelease.tarball_url);

      - name: Download latest release
        run: |
          curl -L "${{ steps.get_release.outputs.tarball_url }}" -o latest_release.tar.gz

      - name: Extract file from release
        run: |
          mkdir release_contents
          tar -xzf latest_release.tar.gz -C release_contents --strip-components=1
          # Replace with the actual file paths
          cp release_contents/path/to/file/in/release public/WorklogAssistant-windows-${{ steps.get_release.outputs.tag_name }}.zip

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit changes
        run: |
          git checkout -b update-from-latest-release
          git add public/WorklogAssistant-windows-${{ steps.get_release.outputs.tag_name }}.zip
          git commit -m "Update Worklog Assistant binary to ${{ steps.get_release.outputs.tag_name }}"

      - name: Push changes
        uses: ad-m/github-push-action@v0.8.0
        with:
          branch: update-from-latest-release
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: update-from-latest-release-${{ steps.get_release.outputs.tag_name }}
          title: "Update Worklog Assistant to ${{ steps.get_release.outputs.tag_name }}"
          body: "Update Workflow Assistant to ${{ steps.get_release.outputs.tag_name }}"
          labels: "automated PR"