name: Update file from latest release

on:
  workflow_dispatch:

permissions:               
  contents: write           
  pull-requests: write

jobs:
  update-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Get latest release info
        id: get_release
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.WORKLOG_GITHUB_TOKEN }}
          script: |
            const { data: latestRelease } = await github.rest.repos.getLatestRelease({
              owner: 'evolvedlight',
              repo: 'WorklogAssistant',
            });
            core.setOutput('tag_name', latestRelease.tag_name);
            core.setOutput('asset_url', latestRelease.assets[0].url);
            core.setOutput('asset_filename', latestRelease.assets[0].name);
            console.log(latestRelease);
            console.log(latestRelease.assets[0].browser_download_url);

      - name: Download latest release
        run: |
          curl -vv -L -H "Authorization: token ${{ secrets.WORKLOG_GITHUB_TOKEN }}" -H "Accept: application/octet-stream" "${{ steps.get_release.outputs.asset_url }}" -o "public/${{ steps.get_release.outputs.asset_filename }}"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.WEB_GITHUB_TOKEN }}
          branch: update-from-latest-release-${{ steps.get_release.outputs.tag_name }}
          base: main
          title: "Update Worklog Assistant to ${{ steps.get_release.outputs.tag_name }}"
          body: "Update Workflow Assistant to ${{ steps.get_release.outputs.tag_name }}"
          labels: "automated PR"
          assignees: evolvedlight